version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: events_db_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: events_db
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - events-net
    env_file:
      - .env

volumes:
  pgdata:

networks:
  events-net: